/*

    Simple Satellite Operations  tcmd_spec.c

    Copyright (C) 2026  Johnathan K Burchill

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// GENERATED TABLE -- name/num_args/readiness columns are produced by
// scripts/gen_tcmd_spec.py from the flight firmware telecommand table
// (tag sat-1-rc3). The trailing arg_types column is NOT emitted by that
// script: it was derived by reading each command's firmware callback to see
// which TCMD_extract_*_arg helper parses each argument, then hand-verified
// (every row's arg_types length matches num_args; the 26 commands whose type
// couldn't be auto-read from a literal-index extractor call -- delegations
// like bulkup64, atoi/enum args, and the multi-arg ADCS loops -- were resolved
// by hand against the firmware). See tcmd_spec.h for the type-code legend.
//
// Regenerating with gen_tcmd_spec.py rewrites the first three columns and
// DROPS arg_types; re-apply this column afterwards (the linter fails open on a
// missing/short arg_types, so a stale regen mis-parses nothing -- it just
// stops catching arg-format errors until the column is restored).
//
// Each row: telecommand name, exact comma-separated arg count, readiness
// (risk) level, and per-argument type codes. The ground linter checks agendas
// against this -- including rejecting arguments the firmware parser would.

#include "tcmd_spec.h"

const char *const TCMD_SPEC_FW_TAG = "sat-1-rc3";

const tcmd_spec_t TCMD_SPEC[] = {
    { "hello_world",                                         0, TCMD_READY_OPERATION,           "" },
    { "obc_firmware_version",                                0, TCMD_READY_OPERATION,           "" },
    { "core_system_stats",                                   0, TCMD_READY_OPERATION,           "" },
    { "get_all_system_thermal_info",                         0, TCMD_READY_OPERATION,           "" },
    { "get_system_time",                                     0, TCMD_READY_OPERATION,           "" },
    { "set_system_time_approx",                              1, TCMD_READY_OPERATION,           "u" },
    { "set_system_time",                                     1, TCMD_READY_OPERATION,           "u" },
    { "correct_system_time",                                 1, TCMD_READY_OPERATION,           "i" },
    { "set_eps_time_based_on_obc_time",                      0, TCMD_READY_OPERATION,           "" },
    { "set_obc_time_based_on_eps_time",                      0, TCMD_READY_OPERATION,           "" },
    { "set_obc_time_based_on_gnss_time",                     0, TCMD_READY_OPERATION,           "" },
    { "set_obc_time_based_on_gnss_pps",                      0, TCMD_READY_OPERATION,           "" },
    { "available_telecommands",                              0, TCMD_READY_OPERATION,           "" },
    { "reboot",                                              0, TCMD_READY_OPERATION,           "" },
    { "exec_blob_from_fs",                                   3, TCMD_READY_RECOVERY_OR_EXPERT,  "sus" },
    { "scan_i2c_bus",                                        1, TCMD_READY_OPERATION,           "s" },
    { "scan_i2c_bus_verbose",                                1, TCMD_READY_OPERATION,           "s" },
    { "system_self_check_failures_as_json",                  0, TCMD_READY_OPERATION,           "" },
    { "system_self_check_as_json",                           0, TCMD_READY_OPERATION,           "" },
    { "obc_get_rbf_state",                                   0, TCMD_READY_OPERATION,           "" },
    { "uart_send_hex",                                       2, TCMD_READY_OPERATION,           "sh" },
    { "uart_send_str",                                       2, TCMD_READY_OPERATION,           "ss" },
    { "uart_send_hex_get_response_hex",                      2, TCMD_READY_OPERATION,           "sh" },
    { "uart_get_last_rx_times_json",                         0, TCMD_READY_OPERATION,           "" },
    { "uart_get_errors_json",                                0, TCMD_READY_OPERATION,           "" },
    { "uart_set_baud_rate",                                  2, TCMD_READY_OPERATION,           "su" },
    { "echo_back_args",                                      1, TCMD_READY_OPERATION,           "s" },
    { "echo_back_uint32_args",                               3, TCMD_READY_OPERATION,           "uuu" },
    { "run_all_unit_tests",                                  0, TCMD_READY_OPERATION,           "" },
    { "demo_blocking_delay",                                 1, TCMD_READY_FLIGHT_TESTING,      "u" },
    { "demo_os_delay",                                       1, TCMD_READY_FLIGHT_TESTING,      "u" },
    { "config_set_int_var",                                  2, TCMD_READY_OPERATION,           "su" },
    { "config_set_str_var",                                  2, TCMD_READY_OPERATION,           "ss" },
    { "config_get_int_var_json",                             1, TCMD_READY_OPERATION,           "s" },
    { "config_get_str_var_json",                             1, TCMD_READY_OPERATION,           "s" },
    { "config_get_all_vars_jsonl",                           0, TCMD_READY_OPERATION,           "" },
    { "config_get_all_int_vars_json",                        0, TCMD_READY_OPERATION,           "" },
    { "flash_activate_each_cs",                              0, TCMD_READY_FLIGHT_TESTING,      "" },
    { "flash_each_is_reachable",                             0, TCMD_READY_OPERATION,           "" },
    { "flash_read_hex",                                      3, TCMD_READY_OPERATION,           "uuu" },
    { "flash_write_hex",                                     3, TCMD_READY_FLIGHT_TESTING,      "uuh" },
    { "flash_erase",                                         2, TCMD_READY_FLIGHT_TESTING,      "uu" },
    { "flash_benchmark_erase_write_read",                    3, TCMD_READY_FLIGHT_TESTING,      "uuu" },
    { "flash_reset",                                         1, TCMD_READY_FLIGHT_TESTING,      "u" },
    { "flash_read_status_register",                          1, TCMD_READY_OPERATION,           "u" },
    { "flash_force_corrupt_filesystem",                      1, TCMD_READY_HIGH_RISK,           "u" },
    { "fs_format_storage",                                   0, TCMD_READY_RECOVERY_OR_EXPERT,  "" },
    { "fs_mount",                                            0, TCMD_READY_OPERATION,           "" },
    { "fs_unmount",                                          0, TCMD_READY_OPERATION,           "" },
    { "fs_list_directory",                                   3, TCMD_READY_OPERATION,           "suu" },
    { "fs_list_directory_json",                              3, TCMD_READY_OPERATION,           "suu" },
    { "fs_make_directory",                                   1, TCMD_READY_OPERATION,           "s" },
    { "fs_write_file_str",                                   2, TCMD_READY_OPERATION,           "ss" },
    { "fs_write_file_hex",                                   3, TCMD_READY_OPERATION,           "suh" },
    { "fs_delete_file",                                      1, TCMD_READY_OPERATION,           "s" },
    { "fs_delete_dir",                                       1, TCMD_READY_OPERATION,           "s" },
    { "fs_read_file_hex",                                    3, TCMD_READY_OPERATION,           "suu" },
    { "fs_read_text_file",                                   3, TCMD_READY_OPERATION,           "suu" },
    { "fs_read_file_sha256_hash_json",                       3, TCMD_READY_OPERATION,           "suu" },
    { "fs_demo_write_then_read",                             1, TCMD_READY_FLIGHT_TESTING,      "s" },
    { "fs_demo_write_random_data",                           3, TCMD_READY_FLIGHT_TESTING,      "suu" },
    { "fs_benchmark_write_read",                             2, TCMD_READY_FLIGHT_TESTING,      "uu" },
    { "fs_get_filesystem_stats_json",                        0, TCMD_READY_OPERATION,           "" },
    { "fs_compress_file_with_heatshrink",                    4, TCMD_READY_OPERATION,           "ssuu" },
    { "fs_count_str_occurrences",                            2, TCMD_READY_OPERATION,           "ss" },
    { "fs_find_nth_str_occurrence",                          3, TCMD_READY_OPERATION,           "ssu" },
    { "fs_count_hex_occurrences",                            2, TCMD_READY_OPERATION,           "sh" },
    { "fs_find_nth_hex_occurrence",                          3, TCMD_READY_OPERATION,           "shu" },
    { "adcs_ack",                                            0, TCMD_READY_OPERATION,           "" },
    { "adcs_set_wheel_speed",                                3, TCMD_READY_OPERATION,           "iii" },
    { "adcs_reset",                                          0, TCMD_READY_OPERATION,           "" },
    { "adcs_identification",                                 0, TCMD_READY_OPERATION,           "" },
    { "adcs_program_status",                                 0, TCMD_READY_OPERATION,           "" },
    { "adcs_communication_status",                           0, TCMD_READY_OPERATION,           "" },
    { "adcs_deploy_magnetometer",                            1, TCMD_READY_OPERATION,           "u" },
    { "adcs_set_run_mode",                                   1, TCMD_READY_OPERATION,           "u" },
    { "adcs_clear_errors",                                   0, TCMD_READY_OPERATION,           "" },
    { "adcs_attitude_control_mode",                          2, TCMD_READY_OPERATION,           "uu" },
    { "adcs_attitude_estimation_mode",                       1, TCMD_READY_OPERATION,           "u" },
    { "adcs_run_once",                                       0, TCMD_READY_OPERATION,           "" },
    { "adcs_set_magnetometer_mode",                          1, TCMD_READY_OPERATION,           "u" },
    { "adcs_set_magnetorquer_output",                        3, TCMD_READY_OPERATION,           "ddd" },
    { "adcs_save_config",                                    0, TCMD_READY_OPERATION,           "" },
    { "adcs_estimate_angular_rates",                         0, TCMD_READY_OPERATION,           "" },
    { "adcs_get_llh_position",                               0, TCMD_READY_OPERATION,           "" },
    { "adcs_get_power_control",                              0, TCMD_READY_OPERATION,           "" },
    { "adcs_set_power_control",                             10, TCMD_READY_OPERATION,           "uuuuuuuuuu" },
    { "adcs_enter_low_power_mode",                           1, TCMD_READY_OPERATION,           "u" },
    { "adcs_track_sun",                                      0, TCMD_READY_OPERATION,           "" },
    { "adcs_set_magnetometer_config",                       15, TCMD_READY_OPERATION,           "ddddddddddddddd" },
    { "adcs_bootloader_clear_errors",                        0, TCMD_READY_OPERATION,           "" },
    { "adcs_set_unix_time_save_mode",                        4, TCMD_READY_OPERATION,           "uuuu" },
    { "adcs_get_unix_time_save_mode",                        0, TCMD_READY_OPERATION,           "" },
    { "adcs_set_sgp4_orbit_params",                          8, TCMD_READY_OPERATION,           "dddddddd" },
    { "adcs_get_sgp4_orbit_params",                          0, TCMD_READY_OPERATION,           "" },
    { "adcs_save_orbit_params",                              0, TCMD_READY_OPERATION,           "" },
    { "adcs_rate_sensor_rates",                              0, TCMD_READY_OPERATION,           "" },
    { "adcs_get_wheel_speed",                                0, TCMD_READY_OPERATION,           "" },
    { "adcs_get_magnetorquer_command",                       0, TCMD_READY_OPERATION,           "" },
    { "adcs_get_raw_magnetometer_values",                    0, TCMD_READY_OPERATION,           "" },
    { "adcs_estimate_fine_angular_rates",                    0, TCMD_READY_OPERATION,           "" },
    { "adcs_get_magnetometer_config",                        0, TCMD_READY_OPERATION,           "" },
    { "adcs_get_commanded_attitude_angles",                  0, TCMD_READY_OPERATION,           "" },
    { "adcs_set_commanded_attitude_angles",                  3, TCMD_READY_OPERATION,           "ddd" },
    { "adcs_set_estimation_params",                         17, TCMD_READY_OPERATION,           "ddddddduuuuuuuuuu" },
    { "adcs_get_estimation_params",                          0, TCMD_READY_OPERATION,           "" },
    { "adcs_set_augmented_sgp4_params",                     17, TCMD_READY_OPERATION,           "ddddddduddudduddu" },
    { "adcs_get_augmented_sgp4_params",                      0, TCMD_READY_OPERATION,           "" },
    { "adcs_set_tracking_controller_target_reference",       3, TCMD_READY_OPERATION,           "ddd" },
    { "adcs_get_tracking_controller_target_reference",       0, TCMD_READY_OPERATION,           "" },
    { "adcs_set_rate_gyro_config",                           7, TCMD_READY_OPERATION,           "uuudddu" },
    { "adcs_get_rate_gyro_config",                           0, TCMD_READY_OPERATION,           "" },
    { "adcs_estimated_attitude_angles",                      0, TCMD_READY_OPERATION,           "" },
    { "adcs_magnetic_field_vector",                          0, TCMD_READY_OPERATION,           "" },
    { "adcs_fine_sun_vector",                                0, TCMD_READY_OPERATION,           "" },
    { "adcs_nadir_vector",                                   0, TCMD_READY_OPERATION,           "" },
    { "adcs_commanded_wheel_speed",                          0, TCMD_READY_OPERATION,           "" },
    { "adcs_igrf_magnetic_field_vector",                     0, TCMD_READY_OPERATION,           "" },
    { "adcs_quaternion_error_vector",                        0, TCMD_READY_OPERATION,           "" },
    { "adcs_estimated_gyro_bias",                            0, TCMD_READY_OPERATION,           "" },
    { "adcs_estimation_innovation_vector",                   0, TCMD_READY_OPERATION,           "" },
    { "adcs_raw_cam1_sensor",                                0, TCMD_READY_OPERATION,           "" },
    { "adcs_raw_cam2_sensor",                                0, TCMD_READY_OPERATION,           "" },
    { "adcs_raw_coarse_sun_sensor_1_to_6",                   0, TCMD_READY_OPERATION,           "" },
    { "adcs_raw_coarse_sun_sensor_7_to_10",                  0, TCMD_READY_OPERATION,           "" },
    { "adcs_cubecontrol_current",                            0, TCMD_READY_OPERATION,           "" },
    { "adcs_measurements",                                   0, TCMD_READY_OPERATION,           "" },
    { "adcs_download_sd_file_by_index",                      1, TCMD_READY_OPERATION,           "u" },
    { "adcs_download_sd_file_by_checksum",                   1, TCMD_READY_OPERATION,           "h" },
    { "adcs_generic_command",                                2, TCMD_READY_OPERATION,           "uh" },
    { "adcs_generic_bootloader_command",                     2, TCMD_READY_OPERATION,           "uh" },
    { "adcs_generic_telemetry_request",                      2, TCMD_READY_OPERATION,           "uu" },
    { "adcs_acp_execution_state",                            0, TCMD_READY_OPERATION,           "" },
    { "adcs_get_current_state_1",                            0, TCMD_READY_OPERATION,           "" },
    { "adcs_save_image_to_sd",                               2, TCMD_READY_OPERATION,           "uu" },
    { "adcs_request_commissioning_telemetry",                3, TCMD_READY_OPERATION,           "uuu" },
    { "adcs_synchronize_unix_time",                          0, TCMD_READY_OPERATION,           "" },
    { "adcs_get_current_unix_time",                          0, TCMD_READY_OPERATION,           "" },
    { "adcs_set_sd_log_config",                              4, TCMD_READY_OPERATION,           "uhuu" },
    { "adcs_get_sd_log_config",                              1, TCMD_READY_OPERATION,           "u" },
    { "adcs_format_sd",                                      0, TCMD_READY_OPERATION,           "" },
    { "adcs_download_index_file",                            2, TCMD_READY_OPERATION,           "uu" },
    { "adcs_set_commissioning_modes",                        2, TCMD_READY_OPERATION,           "uu" },
    { "adcs_erase_sd_file_by_index",                         1, TCMD_READY_OPERATION,           "u" },
    { "adcs_erase_sd_file_by_checksum",                      1, TCMD_READY_OPERATION,           "h" },
    { "adcs_exit_bootloader",                                0, TCMD_READY_OPERATION,           "" },
    { "adcs_convert_to_jpg_by_index",                        3, TCMD_READY_OPERATION,           "uuu" },
    { "adcs_convert_to_jpg_by_checksum",                     3, TCMD_READY_OPERATION,           "huu" },
    { "adcs_get_wheel_currents",                             0, TCMD_READY_OPERATION,           "" },
    { "adcs_get_cubesense_currents",                         0, TCMD_READY_OPERATION,           "" },
    { "adcs_get_misc_currents",                              0, TCMD_READY_OPERATION,           "" },
    { "log_set_sink_enabled_state",                          2, TCMD_READY_OPERATION,           "uu" },
    { "log_set_system_file_logging_enabled_state",           2, TCMD_READY_OPERATION,           "uu" },
    { "log_report_all_sink_enabled_states",                  0, TCMD_READY_OPERATION,           "" },
    { "log_report_all_system_file_logging_states",           0, TCMD_READY_OPERATION,           "" },
    { "log_set_sink_debugging_messages_state",               2, TCMD_READY_OPERATION,           "uu" },
    { "log_set_system_severity_mask",                        2, TCMD_READY_OPERATION,           "uu" },
    { "log_set_system_debugging_messages_state",             2, TCMD_READY_OPERATION,           "uu" },
    { "log_report_messages_from_memory",                     2, TCMD_READY_OPERATION,           "uu" },
    { "log_report_n_latest_messages_from_memory",            1, TCMD_READY_OPERATION,           "u" },
    { "freetos_list_tasks_jsonl",                            0, TCMD_READY_OPERATION,           "" },
    { "freertos_demo_stack_usage",                           1, TCMD_READY_FLIGHT_TESTING,      "u" },
    { "eps_watchdog",                                        0, TCMD_READY_OPERATION,           "" },
    { "eps_system_reset",                                    0, TCMD_READY_RECOVERY_OR_EXPERT,  "" },
    { "eps_no_operation",                                    0, TCMD_READY_OPERATION,           "" },
    { "eps_cancel_operation",                                0, TCMD_READY_OPERATION,           "" },
    { "eps_switch_to_mode",                                  1, TCMD_READY_OPERATION,           "s" },
    { "eps_set_channel_enabled",                             2, TCMD_READY_OPERATION,           "su" },
    { "eps_get_system_status_json",                          0, TCMD_READY_OPERATION,           "" },
    { "eps_get_pdu_overcurrent_fault_state_json",            0, TCMD_READY_OPERATION,           "" },
    { "eps_get_pbu_abf_placed_state_json",                   0, TCMD_READY_OPERATION,           "" },
    { "eps_get_pdu_data_for_channel_json",                   1, TCMD_READY_OPERATION,           "s" },
    { "eps_get_pdu_housekeeping_data_eng_json",              0, TCMD_READY_OPERATION,           "" },
    { "eps_get_pdu_active_channels_data_json",               0, TCMD_READY_OPERATION,           "" },
    { "eps_get_pdu_active_channels_data_run_avg_json",       0, TCMD_READY_OPERATION,           "" },
    { "eps_get_pdu_housekeeping_data_run_avg_json",          0, TCMD_READY_OPERATION,           "" },
    { "eps_get_pbu_housekeeping_data_eng_json",              0, TCMD_READY_OPERATION,           "" },
    { "eps_get_pbu_housekeeping_data_run_avg_json",          0, TCMD_READY_OPERATION,           "" },
    { "eps_get_pcu_housekeeping_data_eng_json",              0, TCMD_READY_OPERATION,           "" },
    { "eps_get_pcu_housekeeping_data_run_avg_json",          0, TCMD_READY_OPERATION,           "" },
    { "eps_get_piu_housekeeping_data_eng_json",              0, TCMD_READY_OPERATION,           "" },
    { "eps_get_piu_housekeeping_data_run_avg_json",          0, TCMD_READY_OPERATION,           "" },
    { "eps_get_enabled_channels_json",                       0, TCMD_READY_OPERATION,           "" },
    { "eps_get_current_battery_percent",                     0, TCMD_READY_OPERATION,           "" },
    { "eps_power_management_set_current_threshold",          2, TCMD_READY_OPERATION,           "su" },
    { "agenda_fetch_json_grouped",                           0, TCMD_READY_OPERATION,           "" },
    { "agenda_fetch_logged_jsonl",                           0, TCMD_READY_OPERATION,           "" },
    { "agenda_delete_all",                                   0, TCMD_READY_OPERATION,           "" },
    { "agenda_delete_by_tssent",                             1, TCMD_READY_OPERATION,           "u" },
    { "agenda_delete_by_name",                               1, TCMD_READY_OPERATION,           "s" },
    { "agenda_enqueue_from_file",                            3, TCMD_READY_OPERATION,           "suu" },
    { "mpi_send_command_get_response_hex",                   1, TCMD_READY_OPERATION,           "h" },
    { "mpi_demo_tx_to_mpi",                                  0, TCMD_READY_GROUND_ONLY,         "" },
    { "mpi_set_transceiver_mode",                            1, TCMD_READY_OPERATION,           "s" },
    { "mpi_enable_active_mode",                              1, TCMD_READY_OPERATION,           "s" },
    { "mpi_disable_active_mode",                             0, TCMD_READY_OPERATION,           "" },
    { "stm32_internal_flash_read",                           2, TCMD_READY_RECOVERY_OR_EXPERT,  "hu" },
    { "stm32_internal_flash_write",                          2, TCMD_READY_HIGH_RISK,           "hh" },
    { "stm32_internal_flash_page_erase",                     3, TCMD_READY_HIGH_RISK,           "uuu" },
    { "stm32_internal_flash_bank_erase",                     1, TCMD_READY_HIGH_RISK,           "u" },
    { "stm32_internal_flash_get_option_bytes",               0, TCMD_READY_HIGH_RISK,           "" },
    { "stm32_internal_flash_get_active_flash_bank",          0, TCMD_READY_HIGH_RISK,           "" },
    { "stm32_internal_flash_set_active_flash_bank",          1, TCMD_READY_HIGH_RISK,           "u" },
    { "stm32_internal_flash_write_file_to_internal_flash",   4, TCMD_READY_HIGH_RISK,           "suuu" },
    { "stm32_internal_flash_calculate_sha256",               2, TCMD_READY_RECOVERY_OR_EXPERT,  "uu" },
    { "ant_reset",                                           1, TCMD_READY_OPERATION,           "s" },
    { "ant_arm_antenna_system",                              1, TCMD_READY_OPERATION,           "s" },
    { "ant_disarm_antenna_system",                           1, TCMD_READY_OPERATION,           "s" },
    { "ant_deploy_antenna",                                  3, TCMD_READY_OPERATION,           "suu" },
    { "ant_start_automated_antenna_deployment",              2, TCMD_READY_OPERATION,           "su" },
    { "ant_deploy_antenna_with_override",                    3, TCMD_READY_OPERATION,           "suu" },
    { "ant_cancel_deployment_system_activation",             1, TCMD_READY_OPERATION,           "s" },
    { "ant_measure_temp",                                    1, TCMD_READY_OPERATION,           "s" },
    { "ant_report_deployment_status",                        1, TCMD_READY_OPERATION,           "s" },
    { "ant_report_antenna_deployment_activation_count",      2, TCMD_READY_OPERATION,           "su" },
    { "ant_report_antenna_deployment_activation_time",       2, TCMD_READY_OPERATION,           "su" },
    { "obc_read_temperature_complex",                        1, TCMD_READY_OPERATION,           "s" },
    { "obc_read_temperature",                                0, TCMD_READY_OPERATION,           "" },
    { "obc_adc_read_vbat_voltage",                           0, TCMD_READY_OPERATION,           "" },
    { "obc_set_stm32_sysclk_to_hse",                         0, TCMD_READY_OPERATION,           "" },
    { "comms_set_rf_switch_control_mode",                    1, TCMD_READY_FLIGHT_TESTING,      "s" },
    { "comms_get_rf_switch_info",                            0, TCMD_READY_OPERATION,           "" },
    { "comms_bulk_file_downlink_start",                      3, TCMD_READY_OPERATION,           "suu" },
    { "comms_bulk_file_downlink_pause",                      0, TCMD_READY_OPERATION,           "" },
    { "comms_bulk_file_downlink_resume",                     0, TCMD_READY_OPERATION,           "" },
    { "comms_bulk_uplink_open_file",                         2, TCMD_READY_OPERATION,           "ss" },
    { "comms_bulk_uplink_close_file",                        0, TCMD_READY_OPERATION,           "" },
    { "comms_bulk_uplink_write_bytes_hex",                   1, TCMD_READY_OPERATION,           "h" },
    { "bulkup16",                                            1, TCMD_READY_OPERATION,           "h" },
    { "comms_bulk_uplink_write_bytes_base64",                1, TCMD_READY_OPERATION,           "b" },
    { "bulkup64",                                            1, TCMD_READY_OPERATION,           "b" },
    { "comms_bulk_uplink_seek",                              1, TCMD_READY_OPERATION,           "u" },
    { "gnss_send_cmd_ascii",                                 1, TCMD_READY_OPERATION,           "s" },
    { "gnss_send_cmd_ascii_get_response_hex",                1, TCMD_READY_OPERATION,           "s" },
    { "gnss_enable_firehose_storage_mode",                   1, TCMD_READY_OPERATION,           "s" },
    { "gnss_disable_firehose_storage_mode",                  0, TCMD_READY_OPERATION,           "" },
    { "camera_setup",                                        0, TCMD_READY_OPERATION,           "" },
    { "camera_test",                                         0, TCMD_READY_RECOVERY_OR_EXPERT,  "" },
    { "camera_change_baud_rate",                             1, TCMD_READY_RECOVERY_OR_EXPERT,  "s" },
    { "camera_capture",                                      2, TCMD_READY_OPERATION,           "ss" },
    { "boom_deploy_timed",                                   2, TCMD_READY_RECOVERY_OR_EXPERT,  "uu" },
    { "boom_self_check",                                     0, TCMD_READY_OPERATION,           "" },
};

const size_t TCMD_SPEC_COUNT = sizeof TCMD_SPEC / sizeof TCMD_SPEC[0];
