#!/usr/bin/env python3
# scripts/gen_tcmd_spec.py -- generate src/proto/tcmd_spec.c from the flight
# firmware's telecommand table.
#
# The ground software lints agendas against exactly the telecommands the
# satellite accepts: their names, argument counts, and readiness levels. That
# truth lives in the firmware's TCMD_telecommand_definitions[] array. Rather
# than hand-copy 200+ entries (and let them drift), this script reads that
# array straight from the firmware and emits the committed C table the ground
# tools compile in. The generated file is checked in so the ground build never
# needs the firmware repo present.
#
# Regenerate when the firmware's telecommand set changes (new flight tag):
#
#   cd ~/src/CalgaryToSpace/CTS-SAT-1-OBC-Firmware
#   git show sat-1-rc3:firmware/Core/Src/telecommands/telecommand_definitions.c \
#     | python3 ~/src/simple_sat_ops/scripts/gen_tcmd_spec.py --tag sat-1-rc3 \
#         --out ~/src/simple_sat_ops/src/proto/tcmd_spec.c
#
# Reads the firmware .c on stdin (or --in <path>); writes the table to --out
# (or stdout). --tag stamps the source firmware tag into the file header.
#
# Copyright (C) 2026  Johnathan K Burchill -- GPLv3 or later.

import argparse
import re
import sys

# firmware readiness enum -> ground enum (same numeric meaning)
READINESS_MAP = {
    "TCMD_READINESS_LEVEL_FOR_OPERATION":          "TCMD_READY_OPERATION",
    "TCMD_READINESS_LEVEL_FOR_RECOVERY_OR_EXPERT": "TCMD_READY_RECOVERY_OR_EXPERT",
    "TCMD_READINESS_LEVEL_FLIGHT_TESTING":         "TCMD_READY_FLIGHT_TESTING",
    "TCMD_READINESS_LEVEL_GROUND_USAGE_ONLY":      "TCMD_READY_GROUND_ONLY",
    "TCMD_READINESS_LEVEL_HIGH_RISK_AND_UNSAFE":   "TCMD_READY_HIGH_RISK",
}

NAME_RE      = re.compile(r'\.tcmd_name\s*=\s*"([^"]*)"')
NARGS_RE     = re.compile(r'\.number_of_args\s*=\s*(\d+)')
READINESS_RE = re.compile(r'\.readiness_level\s*=\s*(TCMD_READINESS_LEVEL_\w+)')


def parse(text):
    # Walk the definition blocks in order. A new `.tcmd_name` starts a new
    # record; `.number_of_args` and `.readiness_level` attach to the record in
    # progress (they follow the name within each struct initializer).
    records = []
    cur = None
    for line in text.splitlines():
        m = NAME_RE.search(line)
        if m:
            if cur is not None:
                records.append(cur)
            cur = {"name": m.group(1), "nargs": 0,
                   "readiness": "TCMD_READY_OPERATION"}
            continue
        if cur is None:
            continue
        m = NARGS_RE.search(line)
        if m:
            cur["nargs"] = int(m.group(1))
            continue
        m = READINESS_RE.search(line)
        if m:
            fw = m.group(1)
            if fw not in READINESS_MAP:
                sys.exit(f"gen_tcmd_spec: unknown readiness level {fw}")
            cur["readiness"] = READINESS_MAP[fw]
    if cur is not None:
        records.append(cur)
    return records


def emit(records, tag, out):
    w = out.write
    w("// GENERATED by scripts/gen_tcmd_spec.py -- DO NOT EDIT BY HAND.\n")
    w(f"// Source: flight firmware telecommand table, tag {tag}.\n")
    w("// Regenerate when the firmware telecommand set changes; see the\n")
    w("// command in scripts/gen_tcmd_spec.py's header comment.\n")
    w("//\n")
    w("// Each row is one telecommand the satellite accepts: its name, the\n")
    w("// exact number of comma-separated args it expects, and its readiness\n")
    w("// (risk) level. The ground linter checks agendas against this.\n")
    w("\n")
    w('#include "tcmd_spec.h"\n\n')
    w(f'const char *const TCMD_SPEC_FW_TAG = "{tag}";\n\n')
    w("const tcmd_spec_t TCMD_SPEC[] = {\n")
    width = max((len(r["name"]) for r in records), default=0) + 2
    for r in records:
        namelit = f'"{r["name"]}",'
        w(f'    {{ {namelit:<{width}} {r["nargs"]:>2}, {r["readiness"]} }},\n')
    w("};\n\n")
    w("const size_t TCMD_SPEC_COUNT = sizeof TCMD_SPEC / sizeof TCMD_SPEC[0];\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tag", default="unknown",
                    help="firmware tag the table is generated from")
    ap.add_argument("--in", dest="infile", default="-",
                    help="firmware telecommand_definitions.c (default: stdin)")
    ap.add_argument("--out", default="-",
                    help="output .c path (default: stdout)")
    args = ap.parse_args()

    text = sys.stdin.read() if args.infile == "-" else open(args.infile).read()
    records = parse(text)
    if not records:
        sys.exit("gen_tcmd_spec: no telecommand definitions found in input")

    out = sys.stdout if args.out == "-" else open(args.out, "w")
    emit(records, args.tag, out)
    if out is not sys.stdout:
        out.close()
    sys.stderr.write(f"gen_tcmd_spec: wrote {len(records)} telecommands "
                     f"(tag {args.tag})\n")


if __name__ == "__main__":
    main()
